export codeC_hello= "Hello from codeC makefile"

#.PHONY: all
all:
	echo "---------------------------"
	echo makefile codeC
	echo "---------------------------"
	echo WORKROOT: ${WORKROOT}
	echo WORKROOT_hello: ${WORKROOT_hello} 
	echo codeA_hello: ${codeA_hello} 
	echo codeB_hello: ${codeB_hello}
	echo codeC_hello: ${codeC_hello}



