#
# ./Makefile
#
PATH_TO_TOP = .
export BUILD_VERSION := $(shell date -u +%Y%m%d_%H%M)
include $(PATH_TO_TOP)/Makefile.common.mk

.PHONY: all help
all:
	echo "nothing for all!!"

help:
	# need to be fixed. Hence, hard-coded!!
	$(HELP_VIEWER) help/makefile.target

